name: Build and Deploy Website

on:
  push:
    branches: main
  pull_request: []

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      RSPM: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install update-copyright
        run: |
          python -m pip install --upgrade pip
          python -m pip install update-copyright

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          crayon.enabled: 'FALSE'

      - name: Install needed packages
        run: |
          install.packages(c('remotes', 'rprojroot', 'renv', 'desc', 'rmarkdown', 'knitr'))
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies for R packages
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')

      - name: Build site
        run: make -B all

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'alisonrclarke/R-archaeology-lesson' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site/
